version: "3.7"
services:
  database2:
    image: mysql:5.7
    container_name: database2
    ports:
      - 3373:3373
    expose:
      - 3373
    volumes:
      - database2:/var/lib/mysql
    environment:
      MYSQL_DATABASE: database2
      MYSQL_USER: user 
      MYSQL_PASSWORD: pasword 
      MYSQL_ROOT_PASSWORD: pasword
volumes:
  database2: